### ISSUE TITLE
NoneType object has no attribute 'group'

### ISSUE THREAD

**Issue by fvanderbiest** [Vampouille/terraform-plan-formatter#1]
$ terraform plan -no-color | terraform-plan-formatter.py

######################
# Modyfing georchestra
######################
    
Traceback (most recent call last):
  File "/home/fvanderbiest/bin/terraform-plan-formatter.py", line 72, in <module>
    parse_diff_line(line, diff_type, current_stack_name)
  File "/home/fvanderbiest/bin/terraform-plan-formatter.py", line 37, in parse_diff_line
    item = matches.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by fvanderbiest** [comment]
on current ppige-prod

**Comment by Vampouille** [comment]
Fixed by https://github.com/Vampouille/terraform-plan-formatter/commit/924e98c3a360464569b98c4a2631d020fb46554a
